### ISSUE TITLE
Unable to train the system

### ISSUE THREAD

**Issue by rohit-takhar** [eth-srl/Nice2Predict#20]
Hi,
I am trying to follow the instructions and run the training but it is throwing some error:
`INFO: Running command line: bazel-bin/n2p/training/train_json
F0216 01:49:19.235635 32541 readerutil.h:89] Check failed: exists(filename) File 'testdata' does not exist!
*** Check failure stack trace: **
@     0x7fb5ff9245cd  google::LogMessage::Fail()
@     0x7fb5ff926433  google::LogMessage::SendToLog()
@     0x7fb5ff92415b  google::LogMessage::Flush()
@     0x7fb5ff926e1e  google::LogMessageFatal::~LogMessageFatal()
@           0x40ee5a  FileInputRecordReader<>::FileInputRecordReader()
@           0x42b44b  FileRecordInput<>::CreateReader()
@           0x42b215  ShuffledCacheInput<>::CreateReader()
@           0x4152b4  ParallelForeachInput<>()
@           0x412097  InitTrain<>()
@           0x410a92  LearningMain<>()
@           0x40d97a  main
@     0x7fb5fecce830  __libc_start_main
@           0x40d4a9  _start
@              (nil)  (unknown)
`
Can somebody please help me in sorting this out? I tried putting json training file with the name **testdata** also but nothing seems to work.

Thanks,
Rohit

**Comment by onponomarev** [comment]
Hi @rohit-takhar !

Sorry for not replying to you that long. I accidentally introduced an incorrect error message. You should provide a dataset using the -input option.

**Comment by onponomarev** [comment]
Fixed in #19

**Comment by rohit-takhar** [comment]
Hi @onponomarev 
Thank you. I was able to train the model. But I am facing couple of issues while running the server. First, there is no **nice2serverproto** target and while running **nice2server**, I don't know the exact path where model is stored(I need to pass it using -model option). I tried looking around but didn't find any files being updated in the directory.
Thanks for your help in advance.

**Comment by onponomarev** [comment]
Hi @rohit-takhar 
When you train a model, n2p saves it to a couple of files named model_{strings,features}. If you don't have such files, that means that something went wrong. Run train with --logtostderr option to know, what. Also, you can try --checkpoints option that will save an intermediate model each training iteration.

**Comment by rohit-takhar** [comment]
Hi @onponomarev,
Thanks for your help! Everything was running fine but it was not dumping the models without any error. I just chamged the model file name with absoulte path to my home directory and it dumped the model.
