### ISSUE TITLE
Get the learned weights

### ISSUE THREAD

**Issue by urialon** [eth-srl/Nice2Predict#7]
Hi,
Is it possible, after training, to get the learned weights for each feature?
This way I'll be able to tell which features are useful and which are not, and next time not even to extract the un-useful features and save extraction time.

Thanks!

**Comment by vraychev** [comment]
You can call:

**Comment by vraychev** [comment]
void GraphInference::PrintDebugInfo()

**Comment by urialon** [comment]
Thanks!
